version: "3.8"

services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - mynetwork

  # backend:
  #   depends_on:
  #     - db
  #   container_name: node-app
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   # volumes: 
  #   #   - ./backend:/app
  #   ports:
  #     - "3000:3000"
  #     - "5555:5555"
  #   env_file:
  #     - backend/.env
  #   networks:
  #     - mynetwork

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3333:3000"
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    networks:
      - mynetwork

networks:
  mynetwork: